apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-bh7l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-bh7l
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-bh7l
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-bh7l
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-bh7l
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-adzk-tenant/status-quarkus-io/statusquarkusio-bh7l@sha256:7c2f8e66aefc7c2d915a24cd9bcef43fb3a860a802150d17469e6020c0360fec
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
